package com.medtrack.triage;

import javax.persistence.*;
import java.time.LocalDateTime;

/**
 * Entity representing a Triage Record generated by the LLM service.
 * Includes all relevant clinical metadata and parsed scores.
 */
@Entity
@Table(name = "triage_records")
public class TriageRecord {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Column(name = "patient_id", nullable = false)
    private String patientId;
    
    @Column(name = "raw_intake_text", columnDefinition = "TEXT")
    private String rawIntakeText;
    
    @Column(name = "generated_summary", columnDefinition = "TEXT")
    private String generatedSummary;
    
    @Column(name = "priority_score")
    private Integer priorityScore;
    
    @Column(name = "recommended_department")
    private String recommendedDepartment;
    
    @Column(name = "created_at")
    private LocalDateTime createdAt;
    
    @Column(name = "processed_by_llm")
    private Boolean processedByLlm;
    
    @Column(name = "confidence_score")
    private Double confidenceScore;

    // Default Constructor
    public TriageRecord() {
        this.createdAt = LocalDateTime.now();
    }

    // Getters and Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    
    public String getPatientId() { return patientId; }
    public void setPatientId(String patientId) { this.patientId = patientId; }
    
    public String getRawIntakeText() { return rawIntakeText; }
    public void setRawIntakeText(String rawIntakeText) { this.rawIntakeText = rawIntakeText; }
    
    public String getGeneratedSummary() { return generatedSummary; }
    public void setGeneratedSummary(String generatedSummary) { this.generatedSummary = generatedSummary; }
    
    public Integer getPriorityScore() { return priorityScore; }
    public void setPriorityScore(Integer priorityScore) { this.priorityScore = priorityScore; }
    
    public String getRecommendedDepartment() { return recommendedDepartment; }
    public void setRecommendedDepartment(String recommendedDepartment) { this.recommendedDepartment = recommendedDepartment; }
    
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    
    public Boolean getProcessedByLlm() { return processedByLlm; }
    public void setProcessedByLlm(Boolean processedByLlm) { this.processedByLlm = processedByLlm; }
    
    public Double getConfidenceScore() { return confidenceScore; }
    public void setConfidenceScore(Double confidenceScore) { this.confidenceScore = confidenceScore; }
    
    @Override
    public String toString() {
        return "TriageRecord{" +
                "id=" + id +
                ", patientId='" + patientId + '\'' +
                ", priorityScore=" + priorityScore +
                ", confidenceScore=" + confidenceScore +
                '}';
    }
}
